### ISSUE TITLE
copyartifacts plugin fails to load as it hasn't been updated to support Python 3

### ISSUE THREAD

**Issue by JohanSF** [linuxserver/docker-beets#47] opened 2019-03-10 16:33 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

You can see the issue here:
![image](https://user-images.githubusercontent.com/6782603/54088044-bdfaee80-4359-11e9-8220-95f84e5c4582.png)
It appears as the plugin is lacking support for Python 3.

The issue also finds discussion here: [https://github.com/sbarakat/beets-copyartifacts/issues/31#issuecomment-282508634](url)
and a working version that I have tested is here: [https://github.com/mverbowski/beets-copyartifacts/blob/master/beetsplug/copyartifacts.py](url)
Of course though that one works, it will not receive updates if the dev becomes active again. - His last commit was on 24-Oct-2017 and RP's also don't seem to be implemented.

Personally I find this plugin very important to my usecase of beets. I was told by Aptalca on the Linuxserver Discord channel to post this issue here.

Regards, Johan

**Comment by thelamer** [comment] 2019-03-10 16:42
Such is the nature of open source , if you are willing to do the bare minimum effort needed to keep that plugin at least functional with a current python env , we can do what we can to point users to it in the documentation.

**Comment by sparklyballs** [comment] 2019-03-10 16:43
i build beets like this with python 3

https://github.com/sparklyballs/beetstest

**Comment by JohanSF** [comment] 2019-03-10 16:53
Is there some way that I can make the container do this at or right after start-up maybe?
`wget -N 'https://github.com/mverbowski/beets-copyartifacts/blob/master/beetsplug/copyartifacts.py' -O '/usr/lib/python3.6/site-packages/beetsplug/copyartifacts.py'`

**Comment by thelamer** [comment] 2019-03-10 17:57
you can bind mount in custom init logic like this: 
```
-v /path/to/script.sh:/etc/cont-init.d/90-custom-config
```
Anything here will be executed before the program starts.

**Comment by hamfactorial** [comment] 2019-03-10 18:21
I found a similar plugin under active development that may be an appropriate substitute.

https://pypi.org/project/beets-extrafiles/#description
https://github.com/Holzhaus/beets-extrafiles

**Comment by JohanSF** [comment] 2019-03-10 19:12
Nice find ham! I hope linuxserver might include this plugin going forward? :D for now I have implemented the solution that thelamer suggested.

**Comment by hamfactorial** [comment] 2019-03-10 19:46
I've confirmed that the extrafiles plugin is a functional replacement for the default behavior of "copyartifacts" using the following configuration in config.yaml:

```
plugins: [...] extrafiles

extrafiles:
    patterns:
        all: '*'
    paths:
        all: $albumpath/
```

I've mapped a script to /etc/cont-init.d/99-userconfig with the following, which installs the plugin on container init (thus surviving updates)

```
#!/usr/bin/with-contenv bash

pip3 install --no-cache-dir -U beets-extrafiles
```

**Comment by JohanSF** [comment] 2019-03-10 20:45
Thanks ham! :D that is much better. I see in his FAQ that he made the extrafiles plugin because the copyartifacts plugin is no longer maintained.

**Comment by thelamer** [comment] 2019-03-10 21:24
Given there is an alternative and we do not need to take any action on our image I am closing this issue.

**Comment by thelamer** [comment] 2019-03-10 21:27
Actually no, sorry re-opening , I just realized we install this by default. 

Ok so : 
 * beets-extrafiles
 * gmusicapi

Are there any other basic defaults we are missing ?

**Comment by JohanSF** [comment] 2019-03-10 21:38
Are you going to deprecate copyartifacts as a default plugin in the container and now add the extrafiles plugin? :)

**Comment by thelamer** [comment] 2019-03-10 21:46
If the plugin spits out a syntax error I do not see a compelling reason to continue to install it.

**Comment by thelamer** [comment] 2019-03-10 21:48
But I need to know from consumers of this program what are the must have plugins, we have an alt issue for the gmusicapi . What are considered must haves that work with the current image?

**Comment by sparklyballs** [comment] 2019-03-10 21:49
good luck instaling 12342342342342342342232 plugins, with a question like that @thelamer

**Comment by sparklyballs** [comment] 2019-03-10 21:51
the current version of beets and using python3 breaks at least one plugin that i'd consider essential 

fetchart

**Comment by JohanSF** [comment] 2019-03-10 21:53
I'd say those that have been mentioned here at and this [list ](https://beets.readthedocs.io/en/v1.3.17/plugins/index.html) is a good start :D

**Comment by thelamer** [comment] 2019-03-10 21:54
Would it make more sense to consume an ENV variable for pip installs on init and drop everything from base that is not core to the app? 

```
-e PIP_INSTALL="package1|package2|package3"
```
The init logic just checks for the names existing in `/usr/lib/python3/dist-packages/` , if not execute a pip install.

**Comment by sparklyballs** [comment] 2019-03-10 21:55
that's a list , not a menu for us to install everything from though.

**Comment by JohanSF** [comment] 2019-03-10 21:56
> that's a list , not a menu for us to install everything from though.

I think your container already has all of those though.

**Comment by sparklyballs** [comment] 2019-03-10 21:57
> Would it make more sense to consume an ENV variable for pip installs on init and drop everything from base that is not core to the app?
> 
> ```
> -e PIP_INSTALL="package1|package2|package3"
> ```
> The init logic just checks for the names existing in `/usr/lib/python3/dist-packages/` , if not execute a pip install.

oh hell no...

part of the support side of things is made easier by a common container between ourselves and users.

that pisses all over that.

**Comment by sparklyballs** [comment] 2019-03-10 21:59
not to mention, 

"i want to install plugin x, but it fails with your fancy env, because the plugin needs 123 extra dependemcies"

**Comment by thelamer** [comment] 2019-03-10 22:01
Yeah that's fine, in the end I do not use this application. 

I leave it to the community of users to determine what is vital. If you need custom beyond that you should fork and build local or exec into the container. 

But we certainly should not be installing a pip package that crashes on exec in our env.

**Comment by sparklyballs** [comment] 2019-03-10 22:06
if that's the rationale, should probably ditch pillow then, because as far as i can see, the current release of beets under python3 causes fetchart to crash out with an unknown extension type.

i would wager any pliugin using pillow would also crash too.

**Comment by sparklyballs** [comment] 2019-03-10 22:09
until there's a new release of beets, i build my own from latest git commit as opposed to a specific version. 

the current release being ~10 months old.

**Comment by hamfactorial** [comment] 2019-03-10 22:12
I've added an Imagemagick install line to my 99-userconfig script (mentioned above) since pillow stopped working after the rebase to python3.

It wasn't relevant to mention earlier, but seems appropriate now!

**Comment by thelamer** [comment] 2019-03-10 22:14
@sparklyballs I do not understand the split here, this repo was spawned by you. 
It is not a massive change to shift to github_commit triggering and build off their head. 
Are you implying this is only a good idea for personal consumption and not for an LSIO image?

**Comment by sparklyballs** [comment] 2019-03-10 22:22
it could be construed as a little wild west. 

but it does at least work  , at least in my usage of it, in everything i've thrown at it. 

i've tagged 30 or so albums with it on this very day, and prolly at least 3 or 4 a day for the last 2 weeks or so.

**Comment by thelamer** [comment] 2019-03-10 22:36
We build a bunch of stuff at head when no other consistent source is provided, what about a split tag here stripping the non functioning stuff out of latest to be what it currently is and having a nightly tag for their git head with all your new logic? 
We really need your help on this one you have a deep understanding of this application and containerizing it. 
As for the surrounding build logic it is just a matter of modifying the jenkins-vars.yml file and running a local template run. This should work for the variables: 
```
---

# jenkins variables
project_name: docker-beets
external_type: github_commit
release_type: prerelease
release_tag: nightly
ls_branch: nightly
repo_vars:
  - BUILD_VERSION_ARG = 'BEETS_VERSION'
  - EXT_GIT_BRANCH = 'master'
  - EXT_USER = 'beetbox'
  - EXT_REPO = 'beets'
  - LS_USER = 'linuxserver'
  - LS_REPO = 'docker-beets'
  - CONTAINER_NAME = 'beets'
  - DOCKERHUB_IMAGE = 'linuxserver/beets'
  - DEV_DOCKERHUB_IMAGE = 'lsiodev/beets'
  - PR_DOCKERHUB_IMAGE = 'lspipepr/beets'
  - DIST_IMAGE = 'alpine'
  - MULTIARCH='true'
  - CI='true'
  - CI_WEB='true'
  - CI_PORT='8337'
  - CI_SSL='false'
  - CI_DELAY='120'
  - CI_DOCKERENV='TZ=US/Pacific'
  - CI_AUTH='user:password'
  - CI_WEBPATH=''
```

And then you can run this to generate the jenkinsfile:
```
docker run --rm \
  -v $(pwd):/tmp \
  -e LOCAL=true \
  linuxserver/jenkins-builder:latest
```

The logic guard for if BEETS_VERSION is set would just need to be modified to something like this: 
https://github.com/linuxserver/docker-bazarr/blob/development/Dockerfile#L15-L18

With this approach normal users can try the program out easily, and people that are power users or even just your average user can shift to the nightly tag for their setup, adopting the inherent risk.

**Comment by sparklyballs** [comment] 2019-03-11 11:05
well i give up, i can get a branch to build , but nothing is getting pushed to docker hub anywhere that i can see. 

i tried making a commit branch that was mutl-arch, but because python3 is fuckerated on armhf , that doesn't work.

so i tried a nightly with non-multi-arch and nothing got pushed anywhere that i can tell.

**Comment by thelamer** [comment] 2019-03-11 18:19
Yeah aarch64 python 3 stuff has been a thorn in our side . On the build it looks like the package check flag was set to true . We use this flag for our weekly runs that reference package versions inside the repo. 
If the versions are the same no push occurs .

**Comment by thelamer** [comment] 2019-03-11 18:57
We just need the qemu bins in the runtime stages and we should be all set on the nightly branch @sparkyballs , it just pushed the current ones .

**Comment by thelamer** [comment] 2019-03-11 21:24
closing will be resolved to the level that was discussed in this thread when this is merged : 
https://github.com/linuxserver/docker-beets/pull/49

**Closed by thelamer** 2019-03-11 21:24 UTC
Labels: enhancement
